### ISSUE TITLE
on deriving intrinsic color

### ISSUE THREAD

**Issue by jpdeleon** [tzdwi/TESS-Gaia#1]
Hi, I am wondering why you had to compute (and the advantage of doing so) the dereddened G_BP-G_RP color using coefficients from Malhan+2018a, when you can simply compute it with 
```
data['(Bp-Rp)_0'] = data['bp_rp'] - data['e_bp_min_rp_val']
```
using the columns already provided by Gaia DR2?

I tried to compare the two results and their difference is approximately normally distributed at 0, probably caused by systematic differences.

**Comment by tzdwi** [comment]
Hmm... I know there's a reason, but it's been long enough that I forget exactly what it was. Maybe a tradeoff on some of the assumptions made? Regardless, I'll add `e_bp_min_rp_val` to the query (and update with the latest sectors) today.

**Comment by tzdwi** [comment]
Turns out that column was already included in the crossmatch. I've updated the notebook to mention it specifically, and done the Sectors 16-21 crossmatch. 

As far as why: it may have something to do with the T_eff-A_G-E(BP-RP) degeneracy? Or maybe because the A_G and E(BP-RP) values have such large errors for individual stars, and the G-band fluxes are higher signal to noise? At the end of the day, if the differences are more-or-less centered on zero, use whichever suites your fancy. If you care a lot about precise extinctions for individual stars (especially with T_eff outside of the fairly narrow range that DR2 was trained on), it might be worth training a model with your stellar evolution tracks of choice (see https://www.aanda.org/articles/aa/pdf/2018/08/aa32516-17.pdf). 

Because I don't save intrinsic magnitudes and colors in the repo anyway, I'm closing this issue.
